app:
  name: socket-test
  port: 3000
  env: development
  api_prefix: /api/v1
  auth_secret: BMeQ2d7RMH8iCkv1BJr407qBQRZejtf6
  #console.log(require('crypto').randomBytes(256).toString('base64'));
  auth_expires_in: 86400 #60*60*24
  auth_refresh_secret: BMeQ2d7RMH8iCkv1BJr407qBQRZejtf6
  auth_refresh_expires_in: 172800 #60*60*24*2
  cookies_secret: BMeQ2d7RMH8iCkv1BJr407qBQRZejtf6

open_api:
  title: Cats example
  description: The cats API description
  version: 1.0